spring.application.name=logistica-urbana

# Base De Datos

spring.datasource.url=jdbc:postgresql://157.230.82.59:5432/logistica_urbana
spring.datasource.username=logistica
spring.datasource.password=logistica
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server

server.port=8080 